version: "3.8"

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: benchuser
      POSTGRES_PASSWORD: benchpass
      POSTGRES_DB: benchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "max_connections=200"

volumes:
  postgres_data:
